# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js image with a version suitable for your application
FROM node:18-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy package files
COPY notion/package.json notion/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the source code
COPY notion/tsconfig.json notion/src ./notion/

# Build the TypeScript application
RUN npm run build --prefix notion

# Use a smaller image to run the application
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy built files from the builder stage
COPY --from=builder /app/notion/build ./build
COPY --from=builder /app/notion/package.json /app/notion/package-lock.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Expose port if necessary
# EXPOSE 3000

# Command to run the application
CMD ["node", "build/index.js"]
